services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        #    image: laravel-app
        container_name: laravel-app
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - laravel

    db:
        image: postgres:15
        container_name: laravel-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

volumes:
    pgdata:

networks:
    laravel:
